* Emacs overlay for Nixpkgs
This is my personal fork of the nix-community emacs-overlay, which includes bundling of nixpkgs and the use of github actions for all builds. To see the full documenation, go [here](https://github.com/nix-community/emacs-overlay#readme). The main differences in this overlay, are it only builds emacsPgtkGcc for linux, and emacsGcc for macos. To get started, you can add the following to your nixos/home-manager config.

#+BEGIN_SRC nix
{
  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/mjlbach/emacs-overlay/archive/feature/flakes.tar.gz;
    }))
  ];
}
#+END_SRC

*** Binary cache
You will want to use my cachix `mjlbach`. Where the
overlay's build artefacts are pushed. See [[https://app.cachix.org/cache/mjlbach][here]] for installation
instructions.

*** Install directly from the overlay
The repository is meant to be used as an overlay as is explained
above. Still, for experimental purposes, you might want to install a
package directly from the overlay. For example, you can install
=emacsGit= from a clone of this repository with the following command:

#+begin_src shell
  nix-build --expr 'with (import <nixpkgs> { overlays = [ (import ./.) ]; }); emacsGit'
#+end_src

#  LocalWords:  EXWM NixOS emacsGit
#  LocalWords:  SRC nixpkgs builtins fetchTarball url
