name: Update Flake

on:
  schedule:
    # every day at 8am UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake update
    - uses: cachix/cachix-action@v10
      with:
        name: mjlbach
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        #    - run: nix-build
    # - run: nix-shell --run "pre-commit run -a"
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: "${{ secrets.GITHUB_TOKEN }}"
    #     commit-message: "[automation] update flake dependencies"
    #     title: "[automation] update flake dependencies"
    #     branch: "automation/update-flake-dependencies"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[automation] update flake dependencies"
